/*
 * Copyright 2012 POLITO 
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mymed_JavaIceWrapper */

#ifndef _Included_mymed_JavaIceWrapper
#define _Included_mymed_JavaIceWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mymed_JavaIceWrapper
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_mymed_JavaIceWrapper_init
  (JNIEnv *, jobject, jstring, jstring, jstring, jint);

/*
 * Class:     mymed_JavaIceWrapper
 * Method:    getConnection
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_mymed_JavaIceWrapper_getConnection
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     mymed_JavaIceWrapper
 * Method:    send
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mymed_JavaIceWrapper_send
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     mymed_JavaIceWrapper
 * Method:    getUsersString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mymed_JavaIceWrapper_getUsersString
  (JNIEnv *, jobject);

/*
 * Class:     mymed_JavaIceWrapper
 * Method:    getInput
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mymed_JavaIceWrapper_getInput__
  (JNIEnv *, jobject);

/*
 * Class:     mymed_JavaIceWrapper
 * Method:    getInput
 * Signature: (Ljava/lang/StringBuffer;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mymed_JavaIceWrapper_getInput__Ljava_lang_StringBuffer_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     mymed_JavaIceWrapper
 * Method:    hasConnection
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_mymed_JavaIceWrapper_hasConnection
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
